version: '3'

services:
  app:
    image: lesson-32:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/library
    ports:
      - 8081:8080
    networks:
      - nw
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27018:27017
    networks:
      - nw

networks:
  nw: