server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

