DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK
(
    ID     BIGINT IDENTITY PRIMARY KEY,
    NAME   VARCHAR(255) UNIQUE NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    ESTIMATION_COUNT BIGINT NOT NULL,
    RESULT BIGINT
);

DROP TABLE IF EXISTS ESTIMATION;
CREATE TABLE ESTIMATION
(
    ID      BIGINT IDENTITY PRIMARY KEY,
    VALUE   BIGINT NOT NULL,
    TASK_ID BIGINT              NOT NULL REFERENCES TASK (ID)
);
